### ISSUE TITLE
Run chrome headless

### ISSUE THREAD

**Issue by steventebrinke** [meteortesting/meteor-browser-tests#10]
The chrome driver does not run chrome headless, which causes my tests to fail since only a headless chrome is installed on our server. Passing `--headless` as an argument at https://github.com/meteortesting/meteor-browser-tests/blob/master/browser/chromedriver.js#L42 fixes my issue. This would be an easy fix, so I can provide a pull request, the only question I have is if there are any downsides to passing `--headless`? That is, can we always run chrome headless, or should this be configurable?

**Comment by aldeed** [comment]
@steventebrinke I honestly can't remember if we left that off for a reason. I'd say your PR should add it by default (breaking change) but check a new env variable to allow people to turn it off.

**Comment by aldeed** [comment]
Thanks for the PR
