### ISSUE TITLE
code coverage support

### ISSUE THREAD

**Issue by hexsprite** [meteortesting/meteor-browser-tests#8]
I'd like to add code coverage support for nightmare (and possibly other backends too if people are excited by that)

I'd propose we add the COVERAGE=1 env flag to turn it on

if that's turned on then we will assume that coverage instrumentation is being taken care of by babel-plugin-istanbul

From an implementation detail perspective I think that nyc can take care of all the saving and reporting of tests.

The only change that is necessary is to copy of the __coverage__ data from the client into the server context so it can be saved and processed by nyc.

I will do some experiments and report back.

**Comment by aldeed** [comment]
Makes sense. I saw some of this in your PR, but it didn't seem to be fully implemented as you describe here. If you want to submit a new PR with the full implementation plus documentation for it in the readme, we can review and merge.

**Comment by aldeed** [comment]
related https://github.com/meteortesting/meteor-mocha/pull/51
